spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investment_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    url: /investments/v3/api-docs

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: investment-service:8084
