spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    config-url: /notifications/v3/api-docs

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: notification-service:8087
