spring:
  datasource:
    url: jdbc:mysql://localhost:3306/startup_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true   # 🔥 VERY IMPORTANT

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: startup-service:8082
