spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: team-service:8085
